apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
  labels:
    type: local
spec:
  storageClassName: localstorage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
      volumeID: vol-02f90e420c5ed2c92
      fsType: ext4